apiVersion: v1
kind: Service
metadata:
  name: casauth
  namespace: backend
  labels:
    app: casauth
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: casauth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casauth
  namespace: backend
  labels:
    app: casauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casauth
  template:
    metadata:
      labels:
        app: casauth
        node: backend
    spec:
      containers:
      - name: casauth-api
        image: reg.fptcompute.com.vn/dev/casauth:0.1
        command: ["auth-api", "--log-file=/var/log/cas/api.log"]
        ports:
        - name: casauth-api-p
          containerPort: 5000
        resources:
          requests:
            memory: 500Mi
            cpu: 1000m
          limits:
            memory: 1Gi
            cpu: 2000m
        volumeMounts:
        - name: casauth-api-log
          mountPath: /var/log/cas/
          readOnly: false
        - name: casauth-cfg-vol
          mountPath: /etc/cas/
          readOnly: true
      - name: casauth-task-manager
        image: reg.fptcompute.com.vn/dev/casauth:0.1
        command: ["auth-tm", "--log-file=/var/log/cas/tm.log"]
        resources:
          requests:
            memory: 500Mi
            cpu: 1000m
          limits:
            memory: 1Gi
            cpu: 2000m
        volumeMounts:
        - name: casauth-tm-log
          mountPath: /var/log/cas/
          readOnly: false
        - name: casauth-cfg-vol
          mountPath: /etc/cas/
          readOnly: true
      volumes:
      - name: casauth-api-log
      - name: casauth-tm-log
      - name: casauth-cfg-vol
        configMap:
          name: casauth-config
      imagePullSecrets:
      - name: privatereg
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: casauth-scaler
  namespace: backend 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: casauth
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: requests-per-second
        target:
          type: AverageValue
          averageValue: 1k