apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: backend
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        node: backend
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.7.17-management
          imagePullPolicy: IfNotPresent
          ports:
            - name: rabbitmq
              containerPort: 5672
            - name: rabbitmq-ui
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: password
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: vhost
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data-storage
          resources:
            requests:
              memory: 1500Mi
              cpu: 200m
            limits:
              memory: 2Gi
              cpu: 300m
      volumes:
        - name: rabbitmq-data-storage
          persistentVolumeClaim:
            claimName: rabbitmq-data
