apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
  namespace: backend
spec:
  storageClassName: rabbitmq
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
