apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rabbitmq
  namespace: backend
metadata:
  name: fast
provisioner: rancher.io/local-path
parameters:
  type: pd-ssd
reclaimPolicy: Retain
