apiVersion: v1
kind: ConfigMap
metadata:
  name: cas-backup-config
  namespace: cas-backup-v2
  labels:
    app: cas-backup-config
data:
  benji.yaml: |
    configurationVersion: '1'
    databaseEngine: mysql+pymysql://root:Cas2020@localhost:3306/cascloud?charset=utf8mb4
    defaultStorage: cassystems
    logFile: /var/log/backup/benji.log
    defaultPath: /backups
    lvm_vg: benji_vg
    lvm_lvthinpool: benji_lvthinpool
    lvm_permit_overcommit: 1.4
    bind_host: 0.0.0.0
    bind_port: 5000
    bind_grpc_port: 55051
    thread_workers: 2
    enable_secure_grpc_messaging: false
    taskmanager_grpc_credential: /tmp
    log_level: INFO
    console_formatter: console-colored

    ios:
      - name: file
        module: file
      - name: rbd
        module: rbd
        configuration:
          simultaneousReads: 3
          simultaneousWrites: 3
          cephConfigFile: /etc/ceph/blk01-hn.conf
          clientIdentifier: admin
          newImageFeatures:
            - RBD_FEATURE_LAYERING
            - RBD_FEATURE_EXCLUSIVE_LOCK
            - RBD_FEATURE_STRIPINGV2
            - RBD_FEATURE_OBJECT_MAP
            - RBD_FEATURE_FAST_DIFF
            - RBD_FEATURE_DEEP_FLATTEN

    storages:
      - name: cassystems
        storageId: 1
        module: file
        configuration:
          path: /backups/cassystems
        node: node1
        user_id: 1

    nodes:
      - name: node1
        host: 172.23.8.46
        port: 55051

    grpc_managers:
      - service: benji.taskmanager.grpc.build.backup_pb2_grpc.add_BackupServiceServicer_to_server
        servicer: benji.taskmanager.grpc.servicers.BackupServicer
      - service: benji.taskmanager.grpc.build.user_pb2_grpc.add_UserServiceServicer_to_server
        servicer: benji.taskmanager.grpc.servicers.UserServicer

    ops_auth:
      username: haidv20@gmail.com
      password: aGFpZHYyMEBnbWFpbC5jb20=
      project_name: haidv20@gmail.com
      endpoint: http://172.18.0.200:5000
      domain_name: opsldap