apiVersion: v1
kind: Service
metadata:
  name: casbackup-mariadb
  namespace: backend
  labels:
    app: casbackup-mariadb
spec:
  type: NodePort
  ports:
    - name: casbackup-mariadb
      port: 3306
      targetPort: 3306
  selector:
    app: casbackup-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: casbackup-db-data
  namespace: backend
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: casbackup-db
  namespace: backend
  labels:
    app: casbackup-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: casbackup-db
  template:
    metadata:
      labels:
        app: casbackup-db
        node: backend
    spec:
      containers:
        - name: casbackup-db
          image: reg.fptcompute.com.vn/dev/casmariadbbk:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: casbackup-db-p
              containerPort: 3306
          env:
            - name: DB_NAME
              value: cascloud
            - name: DB_AUTH_HOST
              value: casauth-mariadb
            - name: DB_ORDER_HOST
              value: casorder-mariadb
            - name: DB_VDC_HOST
              value: casvdc-mariadb
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: password
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: database
          # volumeMounts:
          #   - mountPath: /backups
          #     name: casbackup-data-storage
          #     readOnly: false
          resources:
            requests:
              memory: 100Mi
              cpu: 200m
            limits:
              memory: 1Gi
              cpu: 300m
      # volumes:
      #   - name: casbackup-data-storage
      #     persistentVolumeClaim:
      #       claimName: casbackup-db-data
      imagePullSecrets:
      - name: privatereg
