apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: backend
spec:
  ports:
  - port: 3306
    name: mysql
  - port: 4567
    name: replication-tcp
  # - port: 4567
  #   protocol: UDP
  #   name: replication-udp
  # - port: 4568
  #   name: incremental-state-transfer
  # - port: 4444
  #   name: state-snapshot-transfer
  clusterIP: None
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: backend
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  replicas: 3
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: reg.fptcompute.com.vn/dev/mariadb-galera
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb
              key: database
        ports:
        - containerPort: 3306
          name: database
        volumeMounts:
        # - name: galera-cnf
        #   mountPath: /etc/mysql/conf.d/galera.cnf
        #   subPath: galera.cnf
        # - name: mariadb
        #   mountPath: /var/lib/mysql
        readinessProbe:
          exec:
           command:
           - sh
           - -c
           - mysql -h $HOSTNAME -u $MYSQL_USER -p $MYSQL_PASSWORD $MYSQL_DATABASE -e "SHOW GLOBAL STATUS LIKE 'wsrep_ready';" | grep ON
      # volumes:
      # - name: galera-cnf
      #   configMap:
      #     name: galera-cnf
      imagePullSecrets:
      - name: privatereg
  # volumeClaimTemplates:
  # - metadata:
  #     name: mariadb
  #   spec:
  #     accessModes: ["ReadWriteOnce"]
  #     storageClassName: "local-path"
  #     resources:
  #       requests:
  #         storage: 8Gi