apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data
  namespace: backend
spec:
  storageClassName: mariadb-data
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
