###
# Service for mariadb.
# If you want to access mariadb gui service, you can access by using `kubectl port-forward` command.
# c.f.
#   kubectl port-forward <mariadb_pod_name_here> 3306:3306 -n backend
#   -> then you can access by http://localhost:3306
###
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: backend
  labels:
    app: mariadb
spec:
  type: NodePort
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
