apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: backend
type: Opaque
data:
  # echo -n admin | base64 | pbcopy
  user: YWRtaW4=
  # echo -n Cas@2020 | base64 | pbcopy
  password: Q2FzQDIwMjA=
  # echo -n cascloud | base64 | pbcopy
  database: Y2FzY2xvdWQ=
