apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: backend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJkZXYtcmVnaXN0cnkuZm94Y2xvdWQudm4iOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIllXUnRhVzQ2UTJGelFESXdNakU9IgogICAgICAgICAgICAgICAgfQogICAgICAgIH0sCiAgICAgICAgIkh0dHBIZWFkZXJzIjogewogICAgICAgICAgICAgICAgIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4xNSAobGludXgpIgogICAgICAgIH0KfQ==
