apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
data:
  # echo -n "MdEoYhp3vW4p3uZU" | base64
  RABBITMQ_ERLANG_COOKIE: TWRFb1locDN2VzRwM3VaVQ==
  # echo -n "portal" | base64
  RABBITMQ_DEFAULT_USER: cG9ydGFs
  # echo -n "kgDY2CYUJpYEi45V" | base64
  RABBITMQ_DEFAULT_PASS: a2dEWTJDWVVKcFlFaTQ1Vg==
