version: '3'
services:
  mongodb:
    image: mongo:3
    restart: on-failure
    networks:
      - graylog-net
    volumes:
      - mongodb-vol:/data
    ports:
      - 27017:27017

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: on-failure
    networks:
      - graylog-net
    ports:
      - 9200:9200
      - 9300:9300

  graylog:
    image: graylog/graylog:4.0.1
    environment:
      - GRAYLOG_ELASTICSEARCH_VERSION=7
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # Filebeats
      - 5044-5055:5044-5055
    volumes:
      - elasticsearch-vol:/usr/share/elasticsearch/data
    restart: on-failure
    networks:
      graylog-net:
        ipv4_address: 172.20.0.10

volumes:
  mongodb-vol:
    driver: local
  elasticsearch-vol:
    driver: local
  graylog-vol:
    driver: local

networks:
  graylog-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
