apiVersion: v1
kind: ConfigMap
metadata:
  name: casauth-config
  namespace: backend
  labels:
    app: casauth-config
data:
  cas.conf: |
    [DEFAULT]
    # Show debugging output in logs (sets DEBUG log level output)
    use_syslog = False
    debug = True

    # Address to bind the API server
    bind_host = 0.0.0.0

    # Port the bind the API server to
    bind_port = 5000

    transport_url = rabbit://portal:kgDY2CYUJpYEi45V@rabbitmq:5672/

    # Taskmanager queue name
    taskmanager_queue = auth_taskmanager

    # gRPC
    bind_grpc_port = 50051
    taskmanager_grpc_credential = /etc/cas/credentials/

    require_user_level = 0
    deploy_env = docker


    [database]
    connection = mysql+pymysql://admin:Cas@2020@casauth-mariadb/cascloud?charset=utf8mb4
    idle_timeout = 3600

    [service_mail]
    mail_host = casmail
    mail_grpc_port = 50051

    [service_vdc]
    vdc_host = casvdc
    vdc_taskmanager_queue = vdc_taskmanager
    vdc_transport_url = rabbit://portal:kgDY2CYUJpYEi45V@rabbitmq:5672/

    [wsgi]
    api_secret_key = Fti-Cas-82~d9^&(@!#6%1*7
    app_env = development
    log_level = DEBUG
    workers = 4
    access_token_expiration = 30
    permanent_session_lifetime = 30
    default_limits = 100,10000
    recovery_token_timeout = 3600

    [ldap]
    dc = dc=fptcompute,dc=com,dc=vn
    cn = Manager
    password = mjn7S3vkh3838Gfz
    url = ldap://172.16.0.120
    os_cn = openstack-users
    user_ou = Users
