apiVersion: v1
kind: ConfigMap
metadata:
  name: casmail-config
  namespace: backend
  labels:
    app: casmail-config
data:
  cas.conf: |
    [DEFAULT]
    # Show debugging output in logs (sets DEBUG log level output)
    use_syslog = False
    debug = True

    # Address to bind the API server
    bind_host = 0.0.0.0

    # Port the bind the API server to
    bind_port = 5000

    transport_url = rabbit://portal:kgDY2CYUJpYEi45V@rabbitmq:5672/

    # Taskmanager queue name
    taskmanager_queue = mail_taskmanager

    # gRPC
    bind_grpc_port = 50051
    taskmanager_grpc_credential = /etc/cas/credentials/

    # Admin email
    admin_mail_address = dot3@fpt.com.vn,hungbd4@fpt.com.vn,chienlt@fpt.com.vn,sonlh9@fpt.com.vn,manhdv10@fpt.com.vn,liennst@fpt.com.vn,ftel.fti.cas.alert@fpt.com.vn

    # Dashboard URL
    dashboard_url = https://fptvds.vn

    [api_path]
    auth = https://api.fptvds.vn/auth