apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: backend
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        node: backend
    spec:
      containers:
      - name: postgresql
        image: asia.gcr.io/sencoinex-devel/postgresql:20180927
        env:
        - name: DB_USER
          value: sencoinex
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: password
        - name: DB_NAME
          value: sencoinex_devel
        - name: DB_EXTENSION
          value: pg_trgm
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgresql-data-storage
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            memory: 1500Mi
            cpu: 200m
          limits:
            memory: 3Gi
            cpu: 400m
      volumes:
      - name: postgresql-data-storage
        persistentVolumeClaim:
          claimName: postgresql-data
