apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
  namespace: backend
spec:
  storageClassName: postgresql
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: postgresql-data-disk
    fsType: ext4
