apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: backend
spec:
  storageClassName: postgresql
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
