apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: backend
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-for-analytics
  namespace: backend
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: postgresql-for-analytics
spec:
  type: LoadBalancer
  loadBalancerIP: 172.23.0.6
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
  selector:
    app: postgresql
